---
- name: Install Apache
  apt:
    name: "apache2=2.4.29*"
    state: present
  when: ansible_distribution_version == "18.04"

- name: Copying conf file
  copy:
    src: ../files/apache.conf
    dest: /etc/apache2/apache2.conf
  notify:
  - Restart apache

- name: Start apache
  service:
    name: apache2
    state: started
    enabled: true
  when: ansible_os_family == "Debian"
