---

- hosts: webserver
  remote_user: root
  vars_files:
    - vars/secret.yml
  roles:
    -  { role: add_user }
    -  { role: install_vim }
#  tasks:
#    - name: add_user
#      user:
#        name: "{{ item.name }}"
#        password: "{{ item.password }}"
#      loop:
#        - { name: "lol" , password: "{{ password[0] | password_hash('sha512') }}"}
#        - { name: "supdevinci", password: "{{ password[1] | password_hash('sha512') }}" }
