---
- name: install web server
  apt:
    name: "apache2"
    state: present
  when: ansible_os_family == "Debian"

- name: copying html template
  template:
    src: ../templates/index.html.j2
    dest: /var/www/html/index.html
  notify:
  - Restart apache

- name: Start apache
  service:
    name: apache2
    state: started
    enabled: true
  when: ansible_os_family == "Debian"
